In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
print("Versión:", np.__version__)
print(np.show_config())

Versión: 1.26.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2209613275984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.1
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.3
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system:

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.randint(5, size=(2, 3,5))

In [4]:
#4. Print a.
a

array([[[2, 1, 4, 2, 4],
        [4, 1, 1, 2, 2],
        [4, 0, 1, 1, 2]],

       [[1, 3, 1, 0, 1],
        [3, 3, 3, 1, 0],
        [4, 2, 2, 1, 1]]])

In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b= np.random.randint(1,2, size=(5, 2,3))

b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [6]:
#7. Do a and b have the same size? How do you prove that in Python code?
print("a:", a.size, "b:", b.size)

a: 30 b: 30


In [7]:
#8. Are you able to add a and b? Why or why not?
#print(a+b)
#np.add(a, b) 
print("No es posible sumar a y b porque a no tiene el mismo número de columnas, que b filas")
print("a shape:", a.shape, "b shape:", b.shape)

No es posible sumar a y b porque a no tiene el mismo número de columnas, que b filas
a shape: (2, 3, 5) b shape: (5, 2, 3)


In [8]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c= b.transpose((1,2,0))

print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [9]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d= np.add(a, c) 

print("Funciona porque tienen el mismo shape. a shape: ", a.shape, "d shape:", d.shape)

Funciona porque tienen el mismo shape. a shape:  (2, 3, 5) d shape: (2, 3, 5)


In [10]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print("a:", a, "\n\n", "d:", d)
print("d es igual a +1")

a: [[[2 1 4 2 4]
  [4 1 1 2 2]
  [4 0 1 1 2]]

 [[1 3 1 0 1]
  [3 3 3 1 0]
  [4 2 2 1 1]]] 

 d: [[[3 2 5 3 5]
  [5 2 2 3 3]
  [5 1 2 2 3]]

 [[2 4 2 1 2]
  [4 4 4 2 1]
  [5 3 3 2 2]]]
d es igual a +1


In [11]:
#12. Multiply a and c. Assign the result to e.
e= np.multiply(a, c)

print(e)

[[[2 1 4 2 4]
  [4 1 1 2 2]
  [4 0 1 1 2]]

 [[1 3 1 0 1]
  [3 3 3 1 0]
  [4 2 2 1 1]]]


In [12]:
#13. Does e equal to a? Why or why not?
print("Si, porque e es la multiplicación por 0 de todos los valores de a")

Si, porque e es la multiplicación por 0 de todos los valores de a


In [13]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max= d.max()
d_min= d.min()
d_mean=d.mean()

In [14]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty([2, 3,5], dtype=int)

print(f.shape)

(2, 3, 5)


In [15]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

"\n#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.\nIf a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.\nIf a value equals to d_mean, assign 50 to the corresponding value in f.\nAssign 0 to the corresponding value(s) in f for d_min in d.\nAssign 100 to the corresponding value(s) in f for d_max in d.\nIn the end, f should have only the following values: 0, 25, 50, 75, and 100.\nNote: you don't have to use Numpy in this question.\n"

In [33]:
f=np.where(((d > d_min) & (d<d_mean)), 25, np.where((d > d_mean) & (d<d_max), 75, np.where(d == d_mean, 50, np.where(d == d_max, 100, 0))))

In [ ]:
"""f[(d > d_min) & (d<d_mean)]=25

f[(d > d_mean) & (d<d_max)]=75

f[d == d_mean]=50

f[d == d_max]=100

f[d == d_min]=0
"""

In [ ]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [34]:
print(d)
print(f)

[[[3 2 5 3 5]
  [5 2 2 3 3]
  [5 1 2 2 3]]

 [[2 4 2 1 2]
  [4 4 4 2 1]
  [5 3 3 2 2]]]
[[[ 75  25 100  75 100]
  [100  25  25  75  75]
  [100   0  25  25  75]]

 [[ 25  75  25   0  25]
  [ 75  75  75  25   0]
  [100  75  75  25  25]]]


In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""